export const enum MutationTypes {
    SET_LOADING = 'SET_LOADING',
    SET_ERRORS = 'SET_ERRORS',
    SET_STAFFS = 'SET_STAFFS',
    SET_STAFF = 'SET_STAFF',
    UPDATE_STAFF = 'UPDATE_STAFF',
    DELETE_STAFF = 'DELETE_STAFF',
    SET_TOTAL_PAGES = 'SET_TOTAL_PAGES'
}