export const enum MutationTypes {
    SET_LOADING = 'SET_LOADING',
    SET_ERRORS = 'SET_ERRORS',
    SET_CUSTOMERS = 'SET_CUSTOMERS',
    SET_CUSTOMER = 'SET_CUSTOMER',
    SHOW_CUSTOMER_FORM = 'SHOW_CUSTOMER_FORM',
    SHOW_ADDRESS_FORM = 'SHOW_ADDRESS_FORM', 
    SET_SELECTED_CUSTOMER_ID = 'SET_SELECTED_CUSTOMER_ID'
}