export const enum MutationTypes {
    SET_LOADING = 'SET_LOADING',
    SET_ERRORS = 'SET_ERRORS',
    SET_ADDRESSES = 'SET_ADDRESSES',
    SET_ADDRESS = 'SET_ADDRESS',
    SET_ADDRESS_CUSTOMER = 'SET_ADDRESS_CUSTOMER',
    SET_SELECTED_ADDRESS_ID = 'SET_SELECTED_ADDRESS_ID'
}