export const enum MutationTypes {
    SET_LOADING = 'SET_LOADING',
    SET_ORDERS = 'SET_ORDERS',
    SET_ORDER = 'SET_ORDER',
    SET_ERRORS = 'SET_ERRORS',
    UPDATE_STATUS = 'UPDATE_STATUS',
    ADD_ITEM_ORDER = 'ADD_ITEM_ORDER',
    UPDATE_ORDER_STAFF = 'UPDATE_ORDER_STAFF',
    SET_CURRENT_ORDER = 'SET_CURRENT_ORDER',
    SET_COMMENT = 'SET_COMMENT',
    SET_ORDER_COMPLETE_REDIRECT = 'SET_ORDER_COMPLETE_REDIRECT',
    SET_TOTAL_PAGES = 'SET_TOTAL_PAGES',
    UPDATE_CUSTOMER_ORDER_STATUS = 'UPDATE_CUSTOMER_ORDER_STATUS',
    UPDATE_CUSTOMER_ORDER_STAFF = 'UPDATE_CUSTOMER_ORDER_STAFF'

    // SEARCH_ORDER = 'SEARCH_ORDER' 
}